name: CI

on:
  push:
    branches: [ main, stable, next ]
  pull_request:
    branches: [ main, stable, next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/relm4/relm4/docs:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - "1.75.0"
    env:
        DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: "clippy"
        run: cargo clippy -- --deny warnings

      - name: "build"
        run: cargo build

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: "Check if the formatting is correct"
        run: cargo fmt --all -- --check

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: crate,statics,relm
